### ISSUE TITLE
How do RSEs learn to become RSEs?

### ISSUE THREAD

**Issue by SimonHettrick** [softwaresaved/international-survey#10]
Can we add a question (or more) on this?

**Comment by Oliph** [comment]
Freetext at the end of the survey (alongside 'tools' and 'skills'?)

**Comment by SimonHettrick** [comment]
After "skill2", add a free text box (non-mandatory) saying:

"How did you learn the skills you need to become an RSE?"

**Comment by Oliph** [comment]
done
