### ISSUE TITLE
question about "duration of your current contract" question

### ISSUE THREAD

**Issue by danielskatz** [softwaresaved/international-survey#114]
Is the question:
What is the duration of your current contract?
asked of everyone, or is this just asked based on some previous answer?

I ask because the system of contracts is not how most US employers/employees function, and I'm wondering how to change this.

**Comment by Oliph** [comment]
This question should only appears if people did not choose any permanent option on the type of contract. Is it only this question or the contract question (which type of contract) itself that is problematic for US?

**Comment by danielskatz** [comment]
It's mostly the phrasing, which I have changed now.

I just wanted to be sure I understood the context before changing the phrasing.
