### ISSUE TITLE
currentEmp11 -- Changing text 

### ISSUE THREAD

**Issue by Oliph** [softwaresaved/international-survey#115]
US_17 asked for clarifications on that question. 

The current text is : "What is the duration of your current employment?" and should be changed. Is the following changes is good enough for everyone?:
"What is the total duration of your current employment (in years)?"

Should ask DE_17 if they want to apply the change too

**Comment by Oliph** [comment]
Already applied for the de_17.

**Comment by danielskatz** [comment]
This seems strange - I think most people think of their current employment in years, unless it's just been a short time.

Do we want people to have to multiply years by 12 to get months?  Is there some way we could ask for years, or months if less than one year?

Or, do we care about months?  Could we just ask for years?

**Comment by Oliph** [comment]
Closing: We ask in years
