### ISSUE TITLE
Ask about how people find software (tools) in 2018?

### ISSUE THREAD

**Issue by StephanJanosch** [softwaresaved/international-survey#119]
goal: find out which tools/workflows/habits are used?

**Comment by Oliph** [comment]
@StephanJanosch do we still want to add that?

**Comment by Oliph** [comment]
Is there any suggestions for this issue?

**Comment by danielskatz** [comment]
I don't think we will find anything useful from asking this.  We'll get a bunch of answers, but not anything we can really use.

**Comment by Oliph** [comment]
Closing. Don't seem to raise interest
