### ISSUE TITLE
README needs updating

### ISSUE THREAD

**Issue by danielskatz** [softwaresaved/international-survey#161]
The README says
>In 2017, we have conducted surveys in the UK and in Canada. We now have German and Dutch collaborators, and we are looking at expanding into Norway, South Africa and the US.

But this is not true, since many of these "expansions" happened in 2017.

The README should be updated.

**Comment by Oliph** [comment]
Removed that section and added a more accurate one. See 7ea3abbf181a062aa40dd6c54decec4c73cd4e32

**Comment by danielskatz** [comment]
But there is no link to narrative or data for Canada...

**Comment by Oliph** [comment]
Added the Canada in the different tables. Commit 422a3d03670c2485ffd70e1df501214b7b2077bd
