### ISSUE TITLE
cell 69 of US survey analysis is confusing

### ISSUE THREAD

**Issue by danielskatz** [softwaresaved/international-survey#165]
I don't understand why cell 69 doesn't include "University" in the word cloud, unless this question was just asked of people who didn't work for universities.  Perhaps this could be clarified in https://github.com/softwaresaved/international-survey/blob/master/analysis/results_us_2017_narrative.ipynb ?

**Comment by Oliph** [comment]
That question was only asked if people did not choose "University" at the previous question.

**Comment by danielskatz** [comment]
Can the analysis text say this then?

**Comment by Oliph** [comment]
Fixed: 96066308b47eee9d8888e6e608df699da9c0a209
