### ISSUE TITLE
"User testing" needs to be pinned down

### ISSUE THREAD

**Issue by SimonHettrick** [softwaresaved/international-survey#168]
In the testing questions, we give the option "user testing", but I think people see this as "we give it to them, and they complain if something goes wrong", which isn't the rigorous testing regime we were asking about.

We need to re-word the answers on this question, and potentially add more options, so that we can separate out "give it to the users and wait for complaints" from "employ a board of users to fulfil testing and report on their findings".

**Comment by Oliph** [comment]
Fixed by adding: ""No formal testing but users provide feedback";"Keine formalen Tests aber Nuzter geben Feedback"
