### ISSUE TITLE
RSE and RSD in preamble

### ISSUE THREAD

**Issue by Oliph** [softwaresaved/international-survey#169]
In the preamble to the survey we need to deal with defining RSE/RSD/other title to be sure that people understand they are all the same no matter how they are called (or can be called) in their respective country

**Comment by StephanJanosch** [comment]
https://github.com/softwaresaved/international-survey/blob/master/survey_creation/2017/de/texts/welcome_message.md

**Comment by Oliph** [comment]
Closed: Obsolete
