### ISSUE TITLE
How does the country-specific selection of answers work?

### ISSUE THREAD

**Issue by mrtnhmtz** [softwaresaved/international-survey#178]
currentEmp1 is country specific but not marked with "Y" in the column "country_specific".

- What is the column "country_specific" used for?
- How is the country specific file selected properly?

**Comment by Oliph** [comment]
I need to change the behaviour of it. Right now, it expect a file in each country's folder and use it. It also creates a specific questions with a FREETEXT if the participant is not from any country. 

I need to change it for checking in the main answer_folder if a file exists with the same name to use it by default and if it does not found it, to use a FREETEXT field for the countries that wants that question.  See issue: #183

I close this issue and for any comment, or question, use the #183

**Comment by mrtnhmtz** [comment]
Sorry, I am a bit lost. So here is what I understand:
- We have to set "Y" in the column "country_specific" so that the "survey generator" ensures that the "whatever_de.csv" file in the folder "/answers/countries/de/" will be used to offer the country specific answers.
- In case "/answers/countries/nl/whatever_nl.csv" isn't found then the "survey generator" uses "/answers/whatever.csv".
- In case "/answers/whatever.csv" isn't found then the "survey generator" uses a FREETEXT as default

I'd be happy if you could acknowledge this behaviour or let us know what works different.

However, bullet point 1 and 2 make sense to me. But bullet point 3 seems to cover a case we would run into only if the questions.csv file is not configured properly. So we should avoid the default behaviour described in bullet point 3 and through an error or an hint that something is wrong in the configuration instead.

**Comment by Oliph** [comment]
It works exactly like that. However, it will only create a FREETEXT for the countries that said they wanted the questions. It will not create a FREETEXT for other countries.
