### ISSUE TITLE
Would it be fine to use country specific academic_field.csv answers?

### ISSUE THREAD

**Issue by mrtnhmtz** [softwaresaved/international-survey#180]
For example see fields used in Germany:
- http://www.dfg.de/en/dfg_profile/statutory_bodies/review_boards/subject_areas/index.jsp
- http://www.dfg.de/dfg_profil/gremien/fachkollegien/faecher/index.jsp

**Comment by Oliph** [comment]
Yes, other countries asked for the same thing. 

Closed with b8880c8a61b69790836a1ee96baa17c12aa9bf99

**Comment by mrtnhmtz** [comment]
Needs to be implemented for Germany in 2019. Also the option "Other" has to be added again.
