### ISSUE TITLE
rephrasing question regarding acknowledgement in papers

### ISSUE THREAD

**Issue by benvanwerkhoven** [softwaresaved/international-survey#186]
I believe the current question is a bit ambiguous. Acknowledgement can mean anything from being asked to co-author the paper to being thanked in the acknowledgements. Perhaps we can change the question from Y/N to dropdown with 'included as author', 'acknowledged in the acknowlegements/text/footnotes', 'my software was cited', 'not at all', or similar options.

What do you think?

**Comment by benvanwerkhoven** [comment]
I realized that my remark was a bit incomplete. I know there are some followup questions like: "were you the main author? Y/N", 'are you generally co-author? Y/N', but it would be easier to answer and easier to analyze if this was just collapsed to one question.

**Comment by danielskatz** [comment]
I think that right now, the first question is did you get credit, and the followups are then details.  On the other hand, putting this together into one question is a good idea, if possible.

Actually, anything to shorten the survey is a good idea...

**Comment by Oliph** [comment]
Ok. I changed the survey to reflect your proposition. See 

I removed the question paper1 and added "Not acknowledged" in the paper.csv answer file

See: d7e905f695810e5da981077e18d856f48c52a88c
