### ISSUE TITLE
Answer: paper2mod need translation

### ISSUE THREAD

**Issue by Oliph** [softwaresaved/international-survey#187]
The file https://github.com/softwaresaved/international-survey/blob/master/survey_creation/2018/answers/paper.csv needs the translation for the newly added "not acknowledged" from the commit: d7e905f695810e5da981077e18d856f48c52a88c, following the #186

**Comment by Oliph** [comment]
Also see #193

**Comment by mrtnhmtz** [comment]
Added translation with https://github.com/softwaresaved/international-survey/commit/d7ed1e70ffbd284b2c3b2011312a8938b903d32f

**Comment by Oliph** [comment]
Thanks.
