### ISSUE TITLE
2018 US ethnicity

### ISSUE THREAD

**Issue by danielskatz** [softwaresaved/international-survey#188]
I'm not sure what to do with https://github.com/softwaresaved/international-survey/blob/2018-survey/survey_creation/2018/answers/countries/us/ethnicity.csv

Current US government practice is to ask 2 separate questions, one for race and one for ethnicity:

1 How do you define your race (checkboxes, not radio buttons, so that respondents may report
multiple races):
 - White
 - Black or African American
  - Asian
  - American Indian and Alaska Native
  - Native Hawaiian and Other Pacific Islander
  - some other race
  - do not wish to answer

2 Do you consider yourself Hispanic or Latino 
  - yes
  - no
  - do not wish to answer

**Comment by Oliph** [comment]
You can add a new question that will be specific to US and having both of them. 
If you want to have the checkbox, just specify "MULTIPLE CHOICES"

**Comment by danielskatz** [comment]
I'm not sure how to do that - can you either explain, or if it's easier, you could just add it :)

Also, it really is 2 questions, one with checkboxes and one with radio buttons.

**Comment by Oliph** [comment]
Added: c9da60a0f0e1ce65782776f1c6672c8e8323f6f7

**Comment by danielskatz** [comment]
In the US survey, I only see question 102 which is the the latino one, but I don't see the race question.

**Comment by Oliph** [comment]
Fixed
