### ISSUE TITLE
2018 paper

### ISSUE THREAD

**Issue by danielskatz** [softwaresaved/international-survey#193]
In https://github.com/softwaresaved/international-survey/blob/2018-survey/survey_creation/2018/answers/paper.csv  what about someone who is acknowledged in the acknowledgements section?  (which to me is not the main text)

**Comment by Oliph** [comment]
We can add an option "Acknowledged in the acknowledgements section".
@mrtnhmtz  or @StephanJanosch, is that ok to add a translation for that? 
Just comment here and I will add both at the same time.

**Comment by mrtnhmtz** [comment]
Integrated with https://github.com/softwaresaved/international-survey/commit/f2f80d2ef01b455bfa587bd44aaa03267131458

**Comment by Oliph** [comment]
Closed: Fixed
