### ISSUE TITLE
2018 US previous job

### ISSUE THREAD

**Issue by danielskatz** [softwaresaved/international-survey#194]
For the US version of https://github.com/softwaresaved/international-survey/blob/2018-survey/survey_creation/2018/answers/previous_job.csv  better answers would be
- "This is my first job";"Dies ist meine erster Job"
- "University";"Universität"
- "Private company";"Privatwirtschaft"
- "Government";"Öffentliche Verwaltung"
- "Non-profit organization";"not sure what the German for this is, or if it matters if this is only used in the US version."
"National laboratory";"Nationales Forschungsinstitut"

**Comment by danielskatz** [comment]
Thanks.  It's fine to leave NGO for the US, though I don't expect many people to say this, since in general, the US has lots of non-profits, but almost no NGOs.  The equivalent of NGOs are non-profits, I think.

**Comment by Oliph** [comment]
Closing. fixed
