### ISSUE TITLE
2018 US type contract

### ISSUE THREAD

**Issue by danielskatz** [softwaresaved/international-survey#195]
For the US version of the type of contract:

For the answers, I think the following are reasonable:
- Permanent, funded by institutional funding
- Permanent, as long as funding is available
- Fixed term, funded by institutional funding
- Fixed term, funded by project funding
- Freelancer, consultant, or contractor
- Research/Teaching Assistant (while a student)
- Prefer not to say

**Comment by Oliph** [comment]
I think that is a better proposition than the one I applied to fix #206 (sorry I get lost between all the different issues about contract). I will apply that if I know I can have the translation in time for them

**Comment by mrtnhmtz** [comment]
I understand that "Agency staff" and "Zero hours contract" will be dropped. That would be fine. The German translations for the proposed answers wouldn't change much or not at all. So feel free to make the required changes.

**Comment by Oliph** [comment]
I keep the current version and I don't touch it anynore
