### ISSUE TITLE
2018 US contract questions

### ISSUE THREAD

**Issue by danielskatz** [softwaresaved/international-survey#196]
Hi,

In the current survey, we have:
2	currentEmp9	When did you start your current contract?
2	currentEmp11	What is the duration (in years) of your current contract?

These questions aren't right for the US, where there typically are no contracts.

Can we change the first to:
When did you start working for your current employer?
or
When did you start your current position?

And the second to:
What is the expected duration (in years) of your current employment?
or
What is the expected duration (in years) of your current position?

**Comment by Oliph** [comment]
Fixed
