### ISSUE TITLE
2018 type organisation

### ISSUE THREAD

**Issue by danielskatz** [softwaresaved/international-survey#197]
I'm a bit confused by https://github.com/softwaresaved/international-survey/blob/2018-survey/survey_creation/2018/answers/type_organisation.csv

Isn't a start-up also a private company?

Can we use the same answers for this that we used in previous job?  i.e., for the US, see the comments in https://github.com/softwaresaved/international-survey/issues/194

**Comment by Oliph** [comment]
See #205
