### ISSUE TITLE
New question for AU survey

### ISSUE THREAD

**Issue by manodeep** [softwaresaved/international-survey#198]
In Australia, people are put either on the academic scale (letter-grades A-E, RSCHA) or the professional scale (HEW 1-10). Depending on the answer, the appropriate pay grades should be shown. @Oliph Should @nrmay and I simply add in the question/answers and submit a pull request?

This situation might also be relevant for NZ @nooriyahp

**Comment by Oliph** [comment]
Yes you can simply add a new question. The german version has that along side of the normal salary. It is the question:
socio10de | Please select your renumeration group according to your collective bargaining agreement |   |   | ONE CHOICE | entgeltgruppe_de

**Comment by manodeep** [comment]
Yes we do. Was already on my to-do for today.

**Comment by manodeep** [comment]
Question `soc10de`, seems to asking for "What is your pay-scale" whereas what both AUS/NZL need are "What kind of a pay-scale are you on" (one choice, with options "Academic/Professional/Other); followed by another question depending on the answer. For "Academic" option, the fields in the follow-up question need to come from [academic_levels](https://github.com/softwaresaved/international-survey/blob/2018-survey/survey_creation/2018/answers/countries/aus/levels_academic.csv). For "Professional" option, the fields in the follow-up question need to come from [professional_levels](https://github.com/softwaresaved/international-survey/blob/2018-survey/survey_creation/2018/answers/countries/aus/levels_professional.csv)

I think if the "Other" option is chosen for the first question, then there should be no follow-up question. Thoughts @nrmay @nooriyahp ?

@nooriyahp I see that these two files are not in the `nzl` folder. If NZL follows the same pay-scales, then simply copying the files `countries/aus/levels_*.csv` over to `countries/nzl/` might be sufficient.

**Comment by manodeep** [comment]
@Oliph Thanks for adding in the changes. Looks good! 

In addition to "Academic" and "Professional", there needs to be the "Other" category in the `salary_category` file. Most (may be all) people should fall into the academic or professional classification, but it would be good to know if there was any "Other" option. Perhaps the "Other" option should be presented with a "FREETEXT" answer. @nrmay @nooriyahp

**Comment by nooriyahp** [comment]
Hi,
Thank you for looking into this Manodeep. I like the idea of having 2 pay scales. I am unsure of how  I should add the answers to the 2 payscales for NZ. 
Although we follow something similar here in NZ, the ranges and different and ofcourse the currencies are different too.
I agree that the other should then allow a freetext and do not wish to disclose options

**Comment by Oliph** [comment]
The option "other" is set up in the questions file and not in the individual answer file (there is a column 'other').
That option allows for a freetext. So it should be working as intended here
