### ISSUE TITLE
edits in 2018 English welcome message

### ISSUE THREAD

**Issue by danielskatz** [softwaresaved/international-survey#203]
Why...

You have received this link because you were identified as someone creating scientific software and because you are on one of the mailing list we used to disseminate the survey. There is currently little reliable information about the community of people creating research related software, so we have decided to use this survey to gather information to help funders and other research organisations develop policies. This questionnaire gives you the opportunity to express your views about your current job and give us information about your career path.

Please note that this research is not compulsory and even if you decide to participate, you can withdraw at any moment.

How long...

There are about 80 questions in this survey. It takes about 10 to 15 minutes to complete.

What will happen...

You will continue to the next page and begin to answer questions based on the country you are working from.

Are there any benefits...

We try to help Research Software Developer/Engineer to be recognised at an institutional level. There is no direct individual benefit to answering this survey.

**Comment by manodeep** [comment]
During the Australian RSE Steering Committee meeting today, someone pointed out that we should consider replacing `scientific` with `research`, i.e., replace `scientific software` with `research software`. There is plenty of research in non-scientific fields, and the current wording seemingly excludes all such potential RSE's. I can see two place where such a change would need to be: 

1. `Study about people writing scientific software` -- the headline
2. `... you were identified as someone creating scientific software` -- the first line of the intro

**Comment by Oliph** [comment]
Applied the suggested modifications.
