### ISSUE TITLE
UX issues

### ISSUE THREAD

**Issue by StephanJanosch** [softwaresaved/international-survey#216]
- [x] Numbers entered appear on the far right. Your eyes read from left to right. In the first moment you don't see your entered number. 
- [x] The sorting of the other language is broken. Selects in another language keep the order of the first language.

**Comment by Oliph** [comment]
I will try to fix the issue with the freenumeric. However I think it is not possible to fix the sorting for different languages

**Comment by Oliph** [comment]
I fix the freenumeric
