### ISSUE TITLE
salary - socio4 - translate to german?

### ISSUE THREAD

**Issue by StephanJanosch** [softwaresaved/international-survey#217]
asks for pounds. No one will answer this by their head.

**Comment by mrtnhmtz** [comment]
In 2017 we already addressed it: https://github.com/softwaresaved/international-survey/blob/master/survey_creation/2017/de/listAnswers/salary.csv ... also mentioned as task in #215

**Comment by StephanJanosch** [comment]
dammit...overlooked it there.
