### ISSUE TITLE
a few remaining issues with the survey

### ISSUE THREAD

**Issue by manodeep** [softwaresaved/international-survey#223]
1. The question: *What is the expected duration (in years) of your current position?* is ambiguous for people on fixed-term contracts: Do we mean the years remaining (as on survey-taking date) or the total number of years from the start date. We should add the word "remaining" or "total" to clarify what is intended. 

2. *Othe* still appears as an option (along with *Other:*) in the Australia version for the question *Which university do you work for?*

3. The question *Would you be interested in joining such an organisation?* should only appear after the answer is **No/No Answer** to *Are you a member of an association of Research Software Developers (e.g. UK RSE, DE-RSE, AUS-RSE, CANARIE, …)?*

4. @nooriyahp Do you think "NZ-RSE" should be included in the question *Are you a member of an association of Research Software Developers (e.g. UK RSE, DE-RSE, AUS-RSE, CANARIE, …)?*

Couple of minor issues in the welcome message:

- Extraneous *are* in the sentence -- *who will use the information to conduct further analysis on how Research Software Engineers/Developers* ~~are~~ *develop their code*.
- Missing closing bracket at the end -- *questions about the study (by emailing Simon Hettrick or Olivier Philippe* **)**

----------------
Issues that were raised in the Australian side [here](https://github.com/rse-aunz/rse-au/issues/40) by @mingfangwu  but are relevant for all countries. Potentially requires adding in new questions or new choices in the answers (i.e., something that will likely require translation)

1. The current question *Do you always work with the same researchers, or do you regularly change the researchers you work with?* but a software engineer may not work with the same researcher, but almost the same research group. Does it make sense to have a separate question about research group or combine the two? Perhaps, even as a separate option, "different researchers, same research group"

2. For the question *Do you have an ORCID ID?* Should be options also include: "What is ORCID", "ORCID is not relevant for me" (I have paraphrased @mingfangwu) 
----------------

**Comment by Oliph** [comment]
I applied all the proposition except the two last propositions. 
If we can have the german translation in time, they will be added. 
@StephanJanosch and @mrtnhmtz, can you add it here the translation for the two last propositions? If yes, I will add myself the question (for 1) and modify the answer file (for 2). If not possible we will just skip that for this year.

**Comment by StephanJanosch** [comment]
@Oliph which answer file? Can you name the question via it's code please?

**Comment by Oliph** [comment]
The answer file does not exist because the question is a Y/N right now.  

The code is open1de

**Comment by StephanJanosch** [comment]
Answers for open1de
"What is ORCID?","Was ist eine ORCID?"
Yes,Ja
No,Nein
"ORCID is not relevant for me.","ORCID ist für mich nicht relevant."

**Comment by Oliph** [comment]
Perfect, thank you very much

**Comment by Oliph** [comment]
I added the options for both answer. Thanks for the quick translation
