### ISSUE TITLE
better readable graphs useable for presentations

### ISSUE THREAD

**Issue by StephanJanosch** [softwaresaved/international-survey#238]
Currently the generated graphs are nice for reading them at a screen, but they don't work well for using them on slides. Maybe we can introduce an option to have bigger labels and fatter lines. 

For some graphs I copied data to excel and redid the graphs.

**Comment by Oliph** [comment]
We could add an option to tweaks the plots, but for having tried before, I could not find a way to have clear plots for both the screen and presentation. Usually we redo the graph like you if they are not readable. I guess you also know you can have the plot in full version by right click on it and open the image.

**Comment by StephanJanosch** [comment]
I know about the full res version. Thanks for hinting!

Maybe some people in my reach have a cool idea about this.
