### ISSUE TITLE
No citation for 2018 results + Zenodo archive not up to date

### ISSUE THREAD

**Issue by AlastairKelly** [softwaresaved/international-survey#239]
Hi, I'm trying to cite the 2018 results, but the citation request in the Readme is still marked TODO. Additionally, I was not able to generate an appropriate citation from the Zenodo archive, as it appears it is not updated to include the 2018 survey. I was under the impression that Zenodo was meant to automatically archive new commits once the project was registered (I could be wrong), so there may be something broken in there. If you try to click on the link for the github repo provided by Zenodo under "supplement to," the link is broken, so that may have something to do with it. (The link is https://github.com/softwaresaved/international-survey/tree/2017-v1.1 )

**Comment by Oliph** [comment]
It is fixed with b345ccaa431e2965292b2 (for the released updated on zenodo), and with 5395237 for the added 2018 citation in the README

The links provided (for the 2017 and the 2018) and provided by Zenodo in the "supplement to" should work soon
