### ISSUE TITLE
time1can: change answer option

### ISSUE THREAD

**Issue by SimonHettrick** [softwaresaved/international-survey#40]
People are getting confused by trying to add up the various answers to some idea of "100% of my time".

Let's try and alleviate this by changing "10 (All my time)" to "10 (Most of my time)".

**Comment by Oliph** [comment]
Applying this solution to have the sliders dependents: https://www.limesurvey.org/forum/can-i-do-this-with-limesurvey/105756-2-questions-one-score

**Comment by Oliph** [comment]
Apply the as the irst comment but keep open in case time to apply the solution found in limesurvey forum

**Comment by Oliph** [comment]
won't fix
