### ISSUE TITLE
Changes to Question 2

### ISSUE THREAD

**Issue by npch** [softwaresaved/international-survey#45]
There's a typo for Q2 GSCEs should be GCSEs. However more generally, this question should be structured so that each level is a generic level with examples of qualifications that fit that level - for instance GCSEs are not applicable to older respondents or respondents from Scotland.

**Comment by Oliph** [comment]
fixed. Added "or equivalent" -- (Need @SimonHettrick  to close it)

**Comment by Oliph** [comment]
fixed
