### ISSUE TITLE
NL_17: dropping socio5

### ISSUE THREAD

**Issue by Oliph** [softwaresaved/international-survey#68]
Dropping the question: "How would you describe your ethnic origin?  This refers to people who share the same cultural background and identity, not country of birth or nationality. "

Difficult to ask that in Netherlands

**Comment by Oliph** [comment]
Apply the modification on nl_17.csv

**Comment by StephanJanosch** [comment]
I would like to drop this in Germany as well. Does not feel right somehow. Hard to describe, but this questions refers somehow back to the 1930's

**Comment by benvanwerkhoven** [comment]
We have removed the question for the NL survey.

@StephanJanosch Do you need this issue to remain open as a reminder, or can I close it?

**Comment by StephanJanosch** [comment]
@benvanwerkhoven you can close it.

**Comment by benvanwerkhoven** [comment]
ok!
