### ISSUE TITLE
More practices to ask about

### ISSUE THREAD

**Issue by SimonHettrick** [softwaresaved/international-survey#7]
We ask about tech handover and bus factor, but we could also ask a question about prevalence of other pracitces. Something like:

"How often do you use:"
 - version control
 - continuous integration (maybe "automated build tools")
 - other things...

With a scale from "Never" to "Always" perhaps?

**Comment by Oliph** [comment]
We already have the question: How are your projects typically tested?
I will try to have a more extended list of possible practices to add

**Comment by SimonHettrick** [comment]
We could also add:

testing, cloud computing, HPC, stuff like that

Maybe on Slack

**Comment by Oliph** [comment]
Did not decided
