### ISSUE TITLE
change to hours per week currentEmp12

### ISSUE THREAD

**Issue by benvanwerkhoven** [softwaresaved/international-survey#85]
We'd like to change part-time or full-time selection to an "hours per week" because many people work 36 or 32 hours in NL and consider it full-time

**Comment by benvanwerkhoven** [comment]
change the tag to currentEmp12_nl

**Comment by StephanJanosch** [comment]
But how would you compare a 39 hour week in germany to a 32 hour week in NL if both are regarded as full time? What additional info gives your the amount of hours?

**Comment by benvanwerkhoven** [comment]
Very good point. I'm not that sure what additional info it gives. The main advantage is that in a question where you only have to options 'full time' or 'part time', I would not know what to answer (because I work 32 hours per week). If the question is phrased as "how many hours" I can at least answer the question.

Essentially it provides the same information as 'full time' or 'part time' as long as you define from what number of hours you consider a job to be 'full time'. 

An alternative would be to define what number of hours is considered full time and add that as part of the question to help people answering it.

A reason to not change the answering method right now would be to facilitate international comparison, but it seems that the definition of what is full time varies per country, while a number of hours would be easier to compare. So for next year's survey, I think we should do number of hours.

What do you think?

**Comment by danielskatz** [comment]
If someone in NL works 36 hours/week and considers it full-time, what information is lost by leaving the question the way it is.

I'm also a little concerned people would take "how many hours per week do you work" as asking how many hours they work, as opposed to how many hours they are paid for working...

**Comment by benvanwerkhoven** [comment]
@danielskatz Thank you, that's a very good point. I had not thought of that. I'll leave the question as a choice between part-time and full-time for now to avoid confusion.

As an aside, I think it could be interesting to include an additional question next year on how much hours you work versus how much hours you are paid to work.
