### ISSUE TITLE
paper5 Are you generally acknowledged in the main text of the paper?

### ISSUE THREAD

**Issue by benvanwerkhoven** [softwaresaved/international-survey#87]
During the RSE Conference 2017 it came up that 'acknowledged' is perhaps a bit too vague. One option is to modify this question into "How are you generally acknowledged in scientific papers?"
With the possible answers:
- authorship
- acknowledged in the text and/or acknowledgements
- through citations
- not at all

Just a suggestion, I'm hoping to start a short discussion on the matter, what you do you think?

**Comment by danielskatz** [comment]
This makes sense to me, as long as we can use the responses to also find the equivalent to the UK survey response (by summing the first three).

I assume you are going to make this a single selection option?

If so, you might need to change the question to "How are you most often acknowledged in scientific papers?"

**Comment by StephanJanosch** [comment]
Or as a start you (@benvanwerkhoven) leave for this years survey as it is and for next year we do an international call to check the questions. We also found nice questions to add, but did not for this years survey in germany

**Comment by benvanwerkhoven** [comment]
@StephanJanosch Yes, I think that's a very good idea.

**Comment by Oliph** [comment]
Fixed. all paper* questions are merged into paper2mod and are ONE CHOICE form now
