### ISSUE TITLE
translate universities.csv

### ISSUE THREAD

**Issue by benvanwerkhoven** [softwaresaved/international-survey#88]
come up with list of Dutch Universities

**Comment by StephanJanosch** [comment]
Check on my knime workflow how I extracted universities and institutions from wikidata. Maybe that helps you: 
https://github.com/softwaresaved/international-survey/blob/master/survey_creation/de_17/resources/de_17_resources.knwf

Download Knee from http://knime.org/ and import my workflow.

**Comment by StephanJanosch** [comment]
![screen shot 2017-09-13 at 08 26 36](https://user-images.githubusercontent.com/11651596/30362660-57686aa6-985d-11e7-8448-f7c1f9ee0f71.png)

**Comment by benvanwerkhoven** [comment]
Thanks!
