### ISSUE TITLE
socio4 - salaries

### ISSUE THREAD

**Issue by benvanwerkhoven** [softwaresaved/international-survey#91]
search for data about NL to compare against, if we can't find any simply use the UK scale with numbers converted to euro.

**Comment by StephanJanosch** [comment]
Check 
https://github.com/softwaresaved/international-survey/blob/master/survey_creation/de_17/listAnswers/salary.csv

we already converted the UK groups into € and asked an additional question for the salary group. Because in Germany we have fixed groups.

**Comment by benvanwerkhoven** [comment]
Thanks Stephan! I'll use that one if I can't find any ge

Leaving this here for future reference:
I have found some interesting data regarding university (WO in Dutch) staff: https://www.onderwijsincijfers.nl/kengetallen/wetenschappelijk-onderwijs/personeelwo 
It's in Dutch and contains some population data regarding distributions by job description, male vs female ratio, and by age. No salaries yet, but I'm getting closer.
 
Some more data available at:
https://www.rathenau.nl/nl/page/universitair-personeel-naar-personeelscategorie-wp-en-obp-universiteit-en-hoofdgebied
https://www.rathenau.nl/nl/page/universitair-personeel-naar-personeelscategorie-en-geslacht
https://www.rathenau.nl/nl/page/universitair-personeel-naar-functiecategorie-totaal-en-tijdelijk
Even with comparisons of age by function, male/female by function and age, fixed-term versus permanent positions, etc.

Still no salaries though

**Comment by benvanwerkhoven** [comment]
found some salary info about 2014 in this spreadsheet:
http://vsnu.nl/files/documenten/Feiten_en_Cijfers/website_WOPI_per_31-12-2014.xls

it gives the salary "schalen" per function and by gender, problem is that these "schalen" represent rather large and overlapping ranges of salaries, not really informative.

**Comment by canarie** [comment]
Unsubscribe





________________________________

**Comment by benvanwerkhoven** [comment]
Hi Canarie, if you don't want to receive emails about the activity in this repository, the easiest thing to do is to click the 'Watch' button at the top of the page on GitHub and select whatever option you prefer. All the best, Ben
