### ISSUE TITLE
allow navigation in survey

### ISSUE THREAD

**Issue by StephanJanosch** [softwaresaved/international-survey#96]
Please allow forward/backward navigation.

**Comment by Oliph** [comment]
Done see commit 64a4ba47f175be92e65517e1da10c0ce4742438a

**Comment by Oliph** [comment]
Settings are not modified with the function to_modify(). To fix after refactoring

**Comment by Oliph** [comment]
Fixed 40886d38f534ab069db1249805b97514a29ba0ee
