### ISSUE TITLE
How to config topic for questions 11

### ISSUE THREAD

**Issue by StephanJanosch** [softwaresaved/international-survey#98]

**Comment by StephanJanosch** [comment]
As soon as we have fixed this issue, you can rerun the script @Oliph. Nice to the the survey in action!

**Comment by Oliph** [comment]
I am on that issue now. I close it as soon as I ran the survey

**Comment by Oliph** [comment]
I had to do a workaround. Right now, they will be no header prior to the question as the questions are within the array.

**Comment by Oliph** [comment]
I fixed that issue with the commit: f8f2e1f30f634adf2132156d1b71893284941d57
For now I close and created a separated issue about Text header to array: #99
